name: Generate Resume PDF

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up TeX environment
      run: |
        sudo apt-get install -y make
        make setup
        echo "PDF_OUTPUT_NAME=resume_$(date +'%m_%Y').pdf" >> $GITHUB_ENV
        echo ${{ env.PDF_OUTPUT_NAME }}
      shell: bash

    - name: Build Resume PDF
      run: |
        make build
      working-directory: ${{ github.workspace }}

    - name: Publish PDF as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PDF_OUTPUT_NAME }}
        path: ${{ github.workspace }}/build/${{ env.PDF_OUTPUT }} # Path to the PDF file