name: Generate Resume PDF

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up TeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended
        sudo apt-get install -y inkscape
      shell: bash

    - name: Build Resume PDF
      run: |
        make build
      working-directory: ${{ github.workspace }}

    - name: Publish PDF as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: ${{ github.workspace }}/build/$(TEX_SOURCE)_$(CURRENT_DATE).pdf